name: Sinchi Tribe
favicon: null
layout_spectrum: 0.7395
typography_spectrum: 0.27587
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c18646'
    - '#daa26e'
    - '#442f14'
    - '#7f5238'
  brandStrength: 0.44582548970356584
  lightness: 0.6495494237169623
  saturation: 0
  rhythmicContrast: 0.9031933925580233
purpose: []
